base_url = "https://janbaudisch.dev"
title = "Jan Baudisch"

compile_sass = false

highlight_code = true

build_search_index = false

generate_rss = true

check_external_links = true

taxonomies = [
    {name = "tags", rss = true}
]

theme = "sam"

[extra]
sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "whoami", link = "/about" },
    { text = "projects", link = "/projects" },
    { text = "sourcehut", link = "https://git.sr.ht/~janbaudisch" },
    { text = "github", link = "https://github.com/janbaudisch" },
    { text = "contact", link = "/contact" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = ""
